[project]
authors = ["Maeve Murphy Quinlan <earmmu@leeds.ac.uk>"]
channels = ["conda-forge"]
description = "Building better dashboards"
name = "dashboards"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
plotly = ">=5.24.1,<6"
numpy = ">=2.1.3,<3"
pandas = ">=2.2.3,<3"
itables = ">=2.2.3,<3"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.9.2,<4"
jupyter = ">=1.1.1,<2"
bqplot = ">=0.12.43,<0.13"
bokeh = ">=3.6.1,<4"
bokeh_sampledata = ">=2024.2,<2025"
