[project]
authors = ["Maeve Murphy Quinlan <earmmu@leeds.ac.uk>"]
channels = ["conda-forge"]
description = "Building better dashboards"
name = "dashboards"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
plotly = ">=5.24.1,<6"
numpy = ">=2.1.3,<3"
pandas = ">=2.2.3,<3"
itables = ">=2.2.3,<3"
